eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: content-center
management:
  endpoint:
    health:
      show-details: always
