eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zuul-server
zuul:
  routes:
    user-center:
      path: /users/**
      strip-prefix: false
    content-center:
      path: /posts/shares/**
      strip-prefix: false
    login-center:
      path: /login/**
      strip-prefix: false
    notice-center:
      path: /notices/**
      strip-prefix: false